---
apiVersion: v1
kind: Pod
metadata:
  name: "nginx-pods"
  namespace: "default"
  labels:
    app: "nginx-pods"
spec:
  containers:
    - name: nginx
      image: nginx:1.19
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: port1
          protocol: TCP
      livenessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 1
        periodSeconds: 10
