---
apiVersion: v1
kind: Pod
metadata:
  name: "nginx-pods"
  namespace: "default"
  labels:
    app: "nginx-pods"
spec:
  containers:
    - image: nginx:1.19
      imagePullPolicy: IfNotPresent
      name: nginx
      ports:
        - containerPort: 80
          name: port1
          protocol: TCP
